server:
  port: 9090
  address: 0.0.0.0
spring:
  profiles:
    active: local
  application:
    name: mqy
  # 数据库配置在application-local.yaml中配置

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # 开启json蛇形映射
  jackson:
    property-naming-strategy: SNAKE_CASE

mybatis-plus:
  configuration:
    # 在控制台打印生成的 SQL 语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名自动映射 (数据库 user_name -> 实体类 userName)
    map-underscore-to-camel-case: true

auth:
  token:
    token-name: token
    ttl: 3600000
    # secret-key请配置在application-local.yaml中

aliyun:
  oss:
    bucket-name: hhr-mqy
    endpoint: https://oss-cn-beijing.aliyuncs.com
    region: cn-beijing
